server:
  port: 8090
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  rabbitmq:
    password: admin
    port: 5672
    host: localhost
    username: admin
    queue:
      json:
        fromQueue: fromQueue
        toQueue:  toQueue
    key:
      toKey: producer.to.consumer